name: mycodeforprod

on: [push,workflow_dispatch]
jobs:
  build:
    name: Start working
    runs-on: ubuntu-latest
    timeout-minutes: 9999
    steps:
       - name: Setup and run build
         run: |
          git config --global user.name "Github Actions";git config --global user.email "actions@github.com"
          git clone https://${{ secrets.TOK}}@github.com/iamroot007/cryptx1.git
          sudo npm i -g javascript-obfuscator
          cd cryptx1;javascript-obfuscator static/javascript/graph_utils.js --compact true --deadCodeInjection true --debugProtection true --selfDefending true   --output static/javascript/graph_utils1.js;cp static/javascript/graph_utils1.js static/javascript/graph_utils.js
          git clone https://${{ secrets.TOK1}}@github.com/iamtelegramking/cryptx.git           
